FROM golang:1.25-bookworm AS fsx-builder

RUN apt-get update \
    && apt-get install -y libaio-dev libattr1-dev libacl1-dev xfslibs-dev \
       autoconf automake libtool pkg-config make \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth=1 https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git /tmp/xfstests \
    && cd /tmp/xfstests \
    && make configure \
    && ./configure \
    && make -j$(nproc) \
    && cp ltp/fsx /usr/local/bin/fsx \
    && rm -rf /tmp/xfstests

FROM golang:1.25-bookworm

ENV PATH="/usr/local/go/bin:${PATH}"

RUN apt-get update && apt-get install -y \
    ca-certificates \
    curl \
    fuse \
    e2fsprogs \
    util-linux \
    strace \
    fio \
    busybox-static \
    cmake \
    make \
    && rm -rf /var/lib/apt/lists/*

COPY --from=fsx-builder /usr/local/bin/fsx /usr/local/bin/fsx

WORKDIR /app

CMD ["sleep", "infinity"]
