FROM golang:1.25-bookworm AS fsx-builder

RUN apt-get update \
    && apt-get install -y libaio-dev libattr1-dev libacl1-dev xfslibs-dev \
       autoconf automake libtool pkg-config make \
    && rm -rf /var/lib/apt/lists/* \
    && git clone --depth=1 https://git.kernel.org/pub/scm/fs/xfs/xfstests-dev.git /tmp/xfstests \
    && cd /tmp/xfstests \
    && make configure \
    && ./configure \
    && make -j$(nproc) \
    && cp ltp/fsx /usr/local/bin/fsx \
    && rm -rf /tmp/xfstests

FROM golang:1.25-bookworm AS builder

RUN apt-get update && apt-get install -y cmake && rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    make loophole e2e.test

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    fuse \
    e2fsprogs \
    util-linux \
    strace \
    fio \
    && rm -rf /var/lib/apt/lists/*

COPY --from=fsx-builder /usr/local/bin/fsx /usr/local/bin/fsx
COPY --from=builder /app/loophole /usr/local/bin/loophole
COPY --from=builder /app/e2e.test /usr/local/bin/e2e.test

CMD ["sleep", "infinity"]
