app = "loophole-e2e"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile.test"

[env]
  S3_ENDPOINT = "https://fly.storage.tigris.dev"
  BUCKET = "loophole-e2e"
  LOOPHOLE_MODE = "lwext4fuse"

[[vm]]
  size = "performance-4x"
  memory = "8gb"
